export const tokenToLetterMap = {
  resistance: '!',
  payload: 'B',
  astromech: 'A',
  modification: 'm',
  missile: 'M',
  title: 't',
  torpedo: 'P',
  rotate: 'R',
  reload: '=',
  calculate: 'a',
  charge: 'g',
  lock: 'l',
  hull: '&',
  sl: '4',
  bl: '7',
  s: '8',
  k: '2',
  br: '9',
  sr: '6',
  af: '{',
  ab: '}',
  ar: '|',
  al: '£',
  ar: '¢',
  afr: '¡',
  dodge: '^',
  shield: '*',
  barrel: 'r',
  boost: 'b',
  crit: 'c',
  hit: 'd',
  focus: 'f',
  evade: 'e',
  cloak: 'k',
  ace: 'x',
  talent: 'E',
  ranged: '?',
  configuration: 'n',
  turret: 'U',
  gunner: 'Y',
  any: ')',
  force: 'F',
  sensor: 'S',
  cannon: 'C',
  forcecharge: 'h',
  crew: 'W',
  xp: 'Ì',
  illicit: 'I',
  tech: 'X',
  small: 'Á',
  medium: 'Â',
  large: 'Ã',
  sensitive: 'Î',
  tactical: 'Z',
  stationary: '5',
  to: '>',
  slam: 's',
  stop: '5',
  at: 'p',
  jam: 'j',
  coordinate: 'o',
  reinforce: 'i'
}

export const letterToTokenMap = Object.fromEntries(
  Object.entries(tokenToLetterMap).map(([k, v]) => [v, k])
);
